update dependencies
frinyvonnick/node-html-to-image pull request #194
Opened 2023-03-24 15:52 UTC by OmerMohideen

Updated handlebars and puppeteer dependencies

2023-03-31 16:39 UTC, rvalitov requested changes
Please delete the deprecated packages. They are useless.

2023-03-31 16:39 UTC, rvalitov commented on package.json
> +    "@types/puppeteer": "^5.4.7",
Delete `@types/puppeteer`, because it's deprecated, see https://www.npmjs.com/package/@types/puppeteer

2023-03-31 16:39 UTC, rvalitov commented on package.json
>      "@types/puppeteer-core": "^5.4.0",
Delete @types/puppeteer-core, because it's useless, see https://www.npmjs.com/package/@types/puppeteer-core

2023-04-01 07:53 UTC, rvalitov approved these changes
@frinyvonnick Please merge 🙏 ! 

I desperately need the latest dependencies.

2023-08-04 12:16 UTC, frinyvonnick commented
Hello 👋 Thank you for your contribution. I upgraded these dependencies to latest versions in this pull request : https://github.com/frinyvonnick/node-html-to-image/pull/209 

It has been released in version [4.0.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v4.0.0) 🚀

2023-08-04 12:16 UTC, closed without merging